package com.example.calendar.helpers

const val EVENT_INSTANCE_KEY = "EVENT_INSTANCE_KEY"

const val START_EVENT_KEY = "DATE_BEGIN_KEY"
const val END_EVENT_KEY = "DATE_END_KEY "

const val TYPE_VIEW_KEY = "TYPE_VIEW_KEY"

const val DIALOG_DATE_KEY = "DIALOG_DATE_KEY"

const val START_LIST_EVENT_KEY = "START_LIST_EVENT_KEY"
const val END_LIST_EVENT_KEY = "END_LIST_EVENT_KEY"

const val START_RECURRENCE_RULE = "START_RECURRENCE_RULE"
const val RULE_RECURRENCE_RULE = "RULE_RECURRENCE_RULE"
